import type { Profile, Transaction, ActivityFeed, Achievement } from './supabase';

export const mockCurrentUser: Profile = {
  id: '1',
  username: 'Vaibhav Chaudhary',
  age: 19,
  college: 'Manipal University Jaipur',
  avatar_url: '',
  total_saved: 12450,
  smart_decisions: 34,
  current_streak: 9,
  longest_streak: 18,
  rank: 2,
  xp_points: 2840,
  level: 7,
  created_at: '2024-06-15T00:00:00Z',
  updated_at: new Date().toISOString(),
};

export const mockLeaderboard: Profile[] = [
  {
    id: '2',
    username: 'Priya Sharma',
    age: 20,
    college: 'IIT Delhi',
    avatar_url: '',
    total_saved: 15230,
    smart_decisions: 42,
    current_streak: 12,
    longest_streak: 20,
    rank: 1,
    xp_points: 3580,
    level: 9,
    created_at: '2024-05-10T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  mockCurrentUser,
  {
    id: '3',
    username: 'Rahul Verma',
    age: 18,
    college: 'Delhi University',
    avatar_url: '',
    total_saved: 9870,
    smart_decisions: 28,
    current_streak: 7,
    longest_streak: 15,
    rank: 3,
    xp_points: 2150,
    level: 6,
    created_at: '2024-07-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    username: 'Ananya Singh',
    age: 19,
    college: 'Manipal University Jaipur',
    avatar_url: '',
    total_saved: 8540,
    smart_decisions: 25,
    current_streak: 5,
    longest_streak: 14,
    rank: 4,
    xp_points: 1920,
    level: 5,
    created_at: '2024-06-20T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    username: 'Arjun Patel',
    age: 20,
    college: 'NIT Trichy',
    avatar_url: '',
    total_saved: 7320,
    smart_decisions: 22,
    current_streak: 4,
    longest_streak: 11,
    rank: 5,
    xp_points: 1650,
    level: 5,
    created_at: '2024-06-25T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    username: 'Kavya Reddy',
    age: 19,
    college: 'BITS Pilani',
    avatar_url: '',
    total_saved: 6890,
    smart_decisions: 20,
    current_streak: 6,
    longest_streak: 13,
    rank: 6,
    xp_points: 1580,
    level: 4,
    created_at: '2024-07-05T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    user_id: '1',
    amount: 350,
    recipient_name: 'Swiggy',
    recipient_upi: 'swiggy@paytm',
    category: 'food',
    mood: 'bored',
    is_need: false,
    purchase_reason: 'Impulse',
    guilt_score: 72,
    proceeded: false,
    regretted: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    user_id: '1',
    amount: 150,
    recipient_name: 'BookMyShow',
    recipient_upi: 'bms@paytm',
    category: 'entertainment',
    mood: 'happy',
    is_need: false,
    purchase_reason: 'Planned',
    guilt_score: 25,
    proceeded: true,
    regretted: false,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    user_id: '1',
    amount: 1200,
    recipient_name: 'Amazon',
    recipient_upi: 'amazon@paytm',
    category: 'shopping',
    mood: 'stressed',
    is_need: false,
    purchase_reason: 'Peer Pressure',
    guilt_score: 85,
    proceeded: true,
    regretted: true,
    regret_days: 2,
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    user_id: '1',
    amount: 80,
    recipient_name: 'Uber',
    recipient_upi: 'uber@paytm',
    category: 'transport',
    mood: 'neutral',
    is_need: true,
    purchase_reason: 'Emergency',
    guilt_score: 15,
    proceeded: true,
    regretted: false,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockActivityFeed: ActivityFeed[] = [
  {
    id: '1',
    user_id: '1',
    activity_type: 'avoided',
    title: 'Smart Decision!',
    description: 'Avoided impulse food delivery purchase',
    amount: 350,
    icon: '🎯',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    user_id: '1',
    activity_type: 'purchase',
    title: 'Purchase Made',
    description: 'Movie tickets - Entertainment',
    amount: 150,
    icon: '🎬',
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    user_id: '1',
    activity_type: 'rank_up',
    title: 'Rank Improved!',
    description: 'Climbed to #2 on leaderboard',
    icon: '📈',
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    user_id: '1',
    activity_type: 'achievement',
    title: 'Achievement Unlocked!',
    description: '9-day smart decision streak',
    icon: '🔥',
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    user_id: '1',
    activity_type: 'friend_beat',
    title: 'Friend Alert!',
    description: 'Ananya Singh is catching up to your rank',
    icon: '⚡',
    created_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockAchievements: Achievement[] = [
  {
    id: '1',
    user_id: '1',
    achievement_type: 'streak',
    title: 'Week Warrior',
    description: '7-day smart decision streak',
    icon: '🔥',
    unlocked_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    user_id: '1',
    achievement_type: 'savings',
    title: 'Savings Champion',
    description: 'Saved ₹10,000 total',
    icon: '💰',
    unlocked_at: new Date(Date.now() - 168 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    user_id: '1',
    achievement_type: 'decisions',
    title: 'Smart Shopper',
    description: '25 smart decisions made',
    icon: '🧠',
    unlocked_at: new Date(Date.now() - 240 * 60 * 60 * 1000).toISOString(),
  },
];

export const moodData = [
  {
    mood: '😊 Happy',
    emoji: '😊',
    name: 'Happy',
    avgSpending: 420,
    transactions: 12,
    regretRate: 15,
    overspend: -8,
  },
  {
    mood: '🤩 Excited',
    emoji: '🤩',
    name: 'Excited',
    avgSpending: 680,
    transactions: 8,
    regretRate: 42,
    overspend: 35,
  },
  {
    mood: '😐 Neutral',
    emoji: '😐',
    name: 'Neutral',
    avgSpending: 350,
    transactions: 18,
    regretRate: 22,
    overspend: 0,
  },
  {
    mood: '😰 Stressed',
    emoji: '😰',
    name: 'Stressed',
    avgSpending: 850,
    transactions: 9,
    regretRate: 87,
    overspend: 62,
  },
  {
    mood: '😔 Sad',
    emoji: '😔',
    name: 'Sad',
    avgSpending: 720,
    transactions: 6,
    regretRate: 78,
    overspend: 48,
  },
  {
    mood: '😑 Bored',
    emoji: '😑',
    name: 'Bored',
    avgSpending: 540,
    transactions: 14,
    regretRate: 68,
    overspend: 42,
  },
  {
    mood: '😤 Frustrated',
    emoji: '😤',
    name: 'Frustrated',
    avgSpending: 920,
    transactions: 5,
    regretRate: 92,
    overspend: 71,
  },
];

export const categoryData = [
  { category: 'food', icon: '🍕', name: 'Food', spent: 3450, budget: 5000, percentage: 28 },
  { category: 'shopping', icon: '🛍️', name: 'Shopping', spent: 2800, budget: 4000, percentage: 23 },
  { category: 'entertainment', icon: '🎮', name: 'Entertainment', spent: 1850, budget: 3000, percentage: 15 },
  { category: 'transport', icon: '🚗', name: 'Transport', spent: 1420, budget: 2000, percentage: 12 },
  { category: 'education', icon: '📚', name: 'Education', spent: 2680, budget: 3000, percentage: 22 },
];

export function getRelativeTime(dateString: string): string {
  const now = new Date();
  const date = new Date(dateString);
  const seconds = Math.floor((now.getTime() - date.getTime()) / 1000);

  if (seconds < 60) return 'just now';
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
  if (seconds < 604800) return `${Math.floor(seconds / 86400)}d ago`;
  return `${Math.floor(seconds / 604800)}w ago`;
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(amount);
}